@startuml


class ConnectFour
class Player
class Board
class Goal
class Token
class Turn
class Horizontal
class Vertical
class Diagonal
class InvertedDiagonal
class Color
class Square
class Red
class Yellow
class PutAction
class Column

ConnectFour  *-down-> Board 
ConnectFour  *-down-> "2" Player
ConnectFour *-down-> Turn
Turn -down-> "2" Player
Board *-down-> "7" Column
Square o--> "0..1" Token
Player  *-down-> "0..21" Token
Player *-down-> Color
Player --> Board
Token *-down-> Color
Column *--> "6" Square 
Color <|-- Red
Color <|-- Yellow
Goal <|-- Horizontal
Goal <|-- Vertical
Goal <|-- Diagonal
Goal <|-- InvertedDiagonal


Player o--> Goal
Goal ..> PutAction
Goal ..> "1..4" Column
PutAction .right.> Token
PutAction ..> Column : "target"

@enduml